[package]
name = "thread_rs"
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
rand = "0.8.5"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "file_generator"
path = "src/file_generator.rs"
bench = true
test = false
